import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Mail, Server, Shield, CheckCircle, Copy, ExternalLink, AlertCircle } from 'lucide-react';

const EmailConfigPage = () => {
  const [copiedRecord, setCopiedRecord] = useState(null);

  const dnsRecords = [
    {
      type: 'A',
      name: 'mail.solvy.chain',
      value: '[YOUR_SERVER_IP]',
      priority: '-',
      ttl: '3600',
      status: 'pending',
      description: 'Points mail subdomain to Mailcow server'
    },
    {
      type: 'MX',
      name: 'solvy.chain',
      value: 'mail.solvy.chain',
      priority: '10',
      ttl: '3600',
      status: 'pending',
      description: 'Mail exchange record for incoming emails'
    },
    {
      type: 'TXT (SPF)',
      name: 'solvy.chain',
      value: '"v=spf1 mx ~all"',
      priority: '-',
      ttl: '3600',
      status: 'pending',
      description: 'Sender Policy Framework - prevents spoofing'
    },
    {
      type: 'TXT (DMARC)',
      name: '_dmarc.solvy.chain',
      value: '"v=DMARC1; p=none; rua=mailto:admin@solvy.chain"',
      priority: '-',
      ttl: '3600',
      status: 'pending',
      description: 'Email authentication policy'
    },
    {
      type: 'TXT (DKIM)',
      name: 'dkim._domainkey.solvy.chain',
      value: '[Generated by Mailcow]',
      priority: '-',
      ttl: '3600',
      status: 'pending',
      description: 'Cryptographic email signature'
    }
  ];

  const emailAddresses = [
    {
      category: 'Leadership',
      emails: [
        { address: 'sean@solvy.chain', name: 'Sean Maurice Mayo (SA Nathan)', role: 'Founder & CEO' },
        { address: 'evergreen@solvy.chain', name: 'Evergreen P. Mayo', role: 'Co-Owner & EBL Director' },
        { address: 'marlon@solvy.chain', name: 'Sean Marlon McDaniel II', role: 'QA Lead & SCRUM Specialist' }
      ]
    },
    {
      category: 'Administrative',
      emails: [
        { address: 'admin@solvy.chain', name: 'System Administrator', role: 'Primary admin contact' },
        { address: 'support@solvy.chain', name: 'Customer Support', role: 'User assistance' },
        { address: 'noreply@solvy.chain', name: 'No Reply', role: 'Automated emails' }
      ]
    },
    {
      category: 'Departmental',
      emails: [
        { address: 'info@solvy.chain', name: 'General Information', role: 'General inquiries' },
        { address: 'sales@solvy.chain', name: 'Sales Team', role: 'Sales inquiries' },
        { address: 'qa@solvy.chain', name: 'Quality Assurance', role: 'Testing & QA' },
        { address: 'dev@solvy.chain', name: 'Development Team', role: 'Technical development' }
      ]
    },
    {
      category: 'Business Units',
      emails: [
        { address: 'ebl@solvy.chain', name: 'Evergreen Beauty Lounge', role: 'Beauty services' },
        { address: 'reign@solvy.chain', name: 'Reign Products', role: 'Product sales' },
        { address: 'decidey@solvy.chain', name: 'DECIDEY NGO', role: 'Education & advocacy' }
      ]
    }
  ];

  const copyToClipboard = (text, recordType) => {
    navigator.clipboard.writeText(text);
    setCopiedRecord(recordType);
    setTimeout(() => setCopiedRecord(null), 2000);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900 via-blue-900 to-indigo-900 py-16">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex justify-center mb-6">
            <div className="w-20 h-20 bg-gradient-to-br from-blue-500 to-purple-500 rounded-full flex items-center justify-center">
              <Mail className="w-10 h-10 text-white" />
            </div>
          </div>
          <h1 className="text-5xl font-bold text-white mb-4">Email Configuration</h1>
          <p className="text-xl text-purple-200 mb-6">SOVEREIGNITITY™ Email Infrastructure</p>
          
          <div className="inline-flex items-center gap-2 bg-blue-900/50 backdrop-blur-sm px-6 py-3 rounded-full border border-blue-400/30">
            <Server className="w-5 h-5 text-blue-400" />
            <span className="text-blue-200 font-medium">mail.solvy.chain</span>
            <Badge className="bg-yellow-600">Setup in Progress</Badge>
          </div>
        </div>

        {/* DNS Records Section */}
        <Card className="bg-black/40 border-purple-500/30 mb-8">
          <CardHeader>
            <CardTitle className="text-white flex items-center gap-2">
              <Server className="w-6 h-6 text-purple-400" />
              DNS Configuration Records
            </CardTitle>
            <CardDescription className="text-purple-200">
              Add these records to your DNS provider to enable email functionality
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {dnsRecords.map((record, index) => (
                <div 
                  key={index}
                  className="bg-gradient-to-r from-purple-900/20 to-blue-900/20 rounded-lg p-4 border border-purple-500/20"
                >
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge className="bg-purple-600">{record.type}</Badge>
                        {record.status === 'active' && (
                          <Badge className="bg-green-600">
                            <CheckCircle className="w-3 h-3 mr-1" />
                            Active
                          </Badge>
                        )}
                        {record.status === 'pending' && (
                          <Badge className="bg-yellow-600">
                            <AlertCircle className="w-3 h-3 mr-1" />
                            Pending
                          </Badge>
                        )}
                      </div>
                      <p className="text-sm text-gray-400 mb-2">{record.description}</p>
                      <div className="grid grid-cols-1 md:grid-cols-4 gap-2 text-sm">
                        <div>
                          <span className="text-gray-400">Name:</span>
                          <p className="text-white font-mono">{record.name}</p>
                        </div>
                        <div className="md:col-span-2">
                          <span className="text-gray-400">Value:</span>
                          <p className="text-white font-mono break-all">{record.value}</p>
                        </div>
                        <div>
                          <span className="text-gray-400">Priority:</span>
                          <p className="text-white font-mono">{record.priority}</p>
                        </div>
                      </div>
                    </div>
                    <Button
                      size="sm"
                      onClick={() => copyToClipboard(record.value, record.type)}
                      className="bg-green-600 hover:bg-green-700 ml-4"
                    >
                      {copiedRecord === record.type ? (
                        <CheckCircle className="w-4 h-4" />
                      ) : (
                        <Copy className="w-4 h-4" />
                      )}
                    </Button>
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-6 bg-yellow-900/20 border border-yellow-500/30 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-yellow-400 mt-0.5" />
                <div>
                  <p className="text-yellow-400 font-semibold mb-1">Important Notes</p>
                  <ul className="text-gray-300 text-sm space-y-1">
                    <li>• Replace [YOUR_SERVER_IP] with your actual Mailcow server IP</li>
                    <li>• DKIM record will be generated by Mailcow after setup</li>
                    <li>• DNS propagation can take 24-48 hours</li>
                    <li>• PTR record must be set by your hosting provider</li>
                  </ul>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Email Addresses Section */}
        <Card className="bg-black/40 border-purple-500/30 mb-8">
          <CardHeader>
            <CardTitle className="text-white flex items-center gap-2">
              <Mail className="w-6 h-6 text-blue-400" />
              Planned Email Addresses
            </CardTitle>
            <CardDescription className="text-purple-200">
              Official email addresses for SOVEREIGNITITY™ operations
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {emailAddresses.map((category, idx) => (
                <div key={idx}>
                  <h3 className="text-xl font-bold text-white mb-4">{category.category}</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {category.emails.map((email, emailIdx) => (
                      <div 
                        key={emailIdx}
                        className="bg-gradient-to-r from-purple-900/20 to-blue-900/20 rounded-lg p-4 border border-purple-500/20"
                      >
                        <div className="flex items-start justify-between">
                          <div className="flex-1">
                            <p className="text-blue-400 font-mono font-semibold mb-1">{email.address}</p>
                            <p className="text-white text-sm mb-1">{email.name}</p>
                            <p className="text-gray-400 text-xs">{email.role}</p>
                          </div>
                          <Button
                            size="sm"
                            onClick={() => copyToClipboard(email.address, email.address)}
                            className="bg-green-600 hover:bg-green-700"
                          >
                            {copiedRecord === email.address ? (
                              <CheckCircle className="w-4 h-4" />
                            ) : (
                              <Copy className="w-4 h-4" />
                            )}
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Security & Features */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
          <Card className="bg-black/40 border-green-500/30">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Shield className="w-6 h-6 text-green-400" />
                Security Features
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-green-400 mt-0.5" />
                  <div>
                    <p className="text-white font-semibold">SPF Protection</p>
                    <p className="text-gray-400 text-sm">Prevents email spoofing</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-green-400 mt-0.5" />
                  <div>
                    <p className="text-white font-semibold">DKIM Signing</p>
                    <p className="text-gray-400 text-sm">Cryptographic email authentication</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-green-400 mt-0.5" />
                  <div>
                    <p className="text-white font-semibold">DMARC Policy</p>
                    <p className="text-gray-400 text-sm">Email authentication reporting</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-green-400 mt-0.5" />
                  <div>
                    <p className="text-white font-semibold">SSL/TLS Encryption</p>
                    <p className="text-gray-400 text-sm">Secure email transmission</p>
                  </div>
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-black/40 border-blue-500/30">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Mail className="w-6 h-6 text-blue-400" />
                Email Features
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-blue-400 mt-0.5" />
                  <div>
                    <p className="text-white font-semibold">Webmail (SOGo)</p>
                    <p className="text-gray-400 text-sm">Access email from any browser</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-blue-400 mt-0.5" />
                  <div>
                    <p className="text-white font-semibold">IMAP/SMTP Support</p>
                    <p className="text-gray-400 text-sm">Use any email client</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-blue-400 mt-0.5" />
                  <div>
                    <p className="text-white font-semibold">Calendar & Contacts</p>
                    <p className="text-gray-400 text-sm">Integrated productivity tools</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-blue-400 mt-0.5" />
                  <div>
                    <p className="text-white font-semibold">Mobile Sync</p>
                    <p className="text-gray-400 text-sm">ActiveSync for iOS/Android</p>
                  </div>
                </li>
              </ul>
            </CardContent>
          </Card>
        </div>

        {/* Documentation Links */}
        <Card className="bg-black/40 border-purple-500/30">
          <CardHeader>
            <CardTitle className="text-white">Setup Documentation</CardTitle>
            <CardDescription className="text-purple-200">
              Comprehensive guides for email infrastructure setup
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Button 
                className="bg-purple-600 hover:bg-purple-700 justify-between"
                onClick={() => window.open('/EMAIL_DNS_CONFIGURATION.md', '_blank')}
              >
                <span>DNS Configuration Guide</span>
                <ExternalLink className="w-4 h-4" />
              </Button>
              <Button 
                className="bg-blue-600 hover:bg-blue-700 justify-between"
                onClick={() => window.open('/MAILCOW_M1_SETUP_GUIDE.md', '_blank')}
              >
                <span>Mailcow M1 Setup Guide</span>
                <ExternalLink className="w-4 h-4" />
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Webmail Access */}
        <div className="mt-8 text-center">
          <Card className="bg-gradient-to-r from-purple-900/40 to-blue-900/40 border-purple-500/30 inline-block">
            <CardContent className="pt-6">
              <h3 className="text-2xl font-bold text-white mb-4">Webmail Access</h3>
              <p className="text-gray-300 mb-4">Once configured, access your email at:</p>
              <div className="bg-black/40 rounded-lg p-4 mb-4">
                <p className="text-blue-400 font-mono text-lg">https://mail.solvy.chain/SOGo</p>
              </div>
              <Button 
                className="bg-green-600 hover:bg-green-700"
                onClick={() => window.open('https://mail.solvy.chain/SOGo', '_blank')}
              >
                Open Webmail
                <ExternalLink className="w-4 h-4 ml-2" />
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default EmailConfigPage;

